schemaVersion: 2.1.0
metadata:
  name: folder_based
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8
      env:
        - name: VSCODE_DEFAULT_WORKSPACE
          value: "/projects/openshift_test"
